#35 Add logging
easydigitaldownloads/edd-activecampaign pull request #36
Opened 2021-05-28 22:32 UTC by LisaCee

Issue: #35

Proposed changes:
- Add logging to show user subscription status
- Add logging to show newsletter signup processing
- Update param names and types to match function
- Update author, site and add id to license

2021-06-01 10:14 UTC, ashleyfae requested changes

2021-06-01 10:14 UTC, ashleyfae commented on edd-activecampaign.php
> +			$payment = edd_get_payment( $payment_id );
This needs to be moved back above the `$payment->add_meta()` call.

2021-06-01 18:30 UTC, robincornett commented on edd-activecampaign.php
> +			edd_debug_log( 'ActiveCampaign Debug - User subscribed to email newsletters.' );
Could these two logs include the payment ID maybe so it's clear what order the log is associated with?

2021-06-01 18:30 UTC, robincornett commented on edd-activecampaign.php
> +			edd_debug_log( 'ActiveCampaign Debug - Beginning to process list signup.' );
Maybe this could also include the payment ID just to make it a little more specific?

2021-06-01 20:25 UTC, robincornett commented on edd-activecampaign.php
> +			edd_debug_log( 'ActiveCampaign Debug - Order ' . $payment_id . ': Beginning to process list signup. Order: ' );
Is the duplicate "Order:" at the end of the string intentional?

2021-06-01 20:48 UTC, LisaCee commented on edd-activecampaign.php
> +			edd_debug_log( 'ActiveCampaign Debug - Order ' . $payment_id . ': Beginning to process list signup. Order: ' );
Nope. I failed to save after I updated the text.

2021-06-02 12:02 UTC, ashleyfae approved these changes
This looks great. :raised_hands: 

Next time can you put the license ID stuff in a new issue/PR though? Just since they're unrelated it's best to keep them separate.

2021-06-02 15:14 UTC, robincornett approved these changes

2021-06-02 15:55 UTC, merged