#39 WIP Refresh Lists
easydigitaldownloads/edd-activecampaign pull request #43
Opened 2021-06-20 22:16 UTC by LisaCee

Issue: #39

2021-06-21 09:40 UTC, ashleyfae commented on edd-activecampaign.php
> +		<button class='edd_active_campaign_refresh_lists'><?php esc_html_e( 'Refresh Lists', 'edd-activecampaign' ); ?></button>
Can you switch to double quotes on the class attribute?

2021-06-21 09:41 UTC, ashleyfae commented on edd-activecampaign.php
> +		add_action( 'wp_ajax_my_action', 'edd_active_campaign_refresh_lists' );
Can you move this up to around where you put the enqueue script action? Line 315-ish.

2021-06-21 09:41 UTC, ashleyfae commented
This is looking great so far! :raised_hands:

2021-06-22 06:17 UTC, ashleyfae commented on edd-activecampaign.php
> +			add_action( 'admin_enqueue_scripts', array( $this, 'edd_activecampaign_refresh_lists' ) );
The ajax action you've chosen in JavaScript is:

```js
action: 'edd_activecampaign_refresh_lists',
```

so that's what we'll have to use in the hook name (first argument). The full hook name is `wp_ajax_{your action name}`. So in this case, it's:

```
wp_ajax_edd_activecampaign_refresh_lists
```

Also, not relevant here, but just for learning: if this were a front-end action and not something within the admin area only, you'd need a second identical hook in `wp_ajax_nopriv_{your action name}`

Example: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/ajax-functions.php#L179-L180

But not relevant here, as this is an admin action only.

2021-06-22 06:21 UTC, ashleyfae commented on edd-activecampaign.php
> +		public function edd_activecampaign_refresh_lists( $args ) {
Because we're inside a class, we don't need the `edd_activecampaign_` name prefix here. The class already namespaces it.

Could you adjust this one and the scripts method accordingly? (And don't forget they also need updating in the hooks so they still match.) But for the scripts one, let's maybe go with `load_admin_scripts()`.

2021-06-24 10:18 UTC, ashleyfae requested changes

2021-06-24 10:18 UTC, ashleyfae commented on edd-activecampaign.php
> +			wp_enqueue_script( 'load_admin_scripts', $this->plugin_url . 'assets/js/scripts.js', array( 'jquery' ) );
```suggestion
			wp_enqueue_script( 'edd-activecampaign', $this->plugin_url . 'assets/js/scripts.js', array( 'jquery' ) );
```

That first parameter is like the ID of the script, so in this case it does need to be a prefixed, unique name for this JavaScript file.

2021-06-24 10:18 UTC, ashleyfae commented on assets/js/scripts.js
> +		button.data( 'nonce' );
This needs to be moved into `data` like this:

```js
data = {
	action: 'edd_activecampaign_refresh_lists',
	nonce: button.data( 'nonce' )
};
```

2021-06-24 10:18 UTC, ashleyfae commented on edd-activecampaign.php
> +		public function refresh_lists( $args ) {
Sorry I didn't catch this before. The `$args` parameter can be removed, then everywhere you use it below should be replaced with `$_POST`.

So instead of `empty( $args['nonce'] )` you would do `empty( $_POST['nonce'] )`

2021-06-24 10:18 UTC, ashleyfae commented on edd-activecampaign.php
> +			$lists = get_lists();
```suggestion
			$lists = $this->get_lists();
```

In this case, `get_lists()` is a method of the class we're in, so you have to call it using `$this->get_lists()`.

2021-06-24 10:18 UTC, ashleyfae commented on edd-activecampaign.php
> +			return wp_send_json_success( 'SUCCESS', $lists );
```suggestion
			wp_send_json_success( $lists );
```

1. In this case no `return` is needed, because `wp_send_json_success()` handles sending the JSON data and exiting, so we don't need a return statement.
2. We only need to send back `$lists`, we don't need a string or indicator that it was successful. The `wp_send_json_success()` function handles that part. So with this change, the ajax call will return an object like this:

```json
{"success":true,"data":{"1":"EDD Default List","2":"EDD SL Product","3":"EDD Commission"}}
```

So it already includes `"success": true` for us, which is nifty.

2021-07-01 12:21 UTC, ashleyfae commented
@LisaCee Code as per slack:

<details>
<summary>Option 1 solution</summary>

```php
public function hooks() {
    // We're inside the hooks() method that already exists.
    add_filter( 'edd_after_setting_output', array( $this, 'add_refresh_button_to_settings_dropdown' ), 10, 2 );
}

public function add_refresh_button_to_settings_dropdown( $output, $args ) {
	if ( empty( $args['id'] ) || 'eddactivecampaign_list' !== $args['id'] ) {
		return $output;
	}

	// Note: the nonce needs adding to teh button and text needs to be translation-ready... I did this quickly.
	$button = '<button class="edd_activecampaign_refresh_lists button" data-format="dropdown">Refresh Lists</button>';

	return str_replace( '<p', $button . '<p', $output );
}
```

</details>

2021-07-20 14:43 UTC, robincornett commented on edd-activecampaign.php
> +			echo '<div class="edd_activecampaign_lists" id="edd_activecampaign_checkbox_lists">';
What would you think of using the new [EDD forms markup](https://github.com/easydigitaldownloads/easy-digital-downloads/wiki/Form-Input-Markup) in here?

2021-07-20 14:47 UTC, ashleyfae commented on assets/js/scripts.js
> +						text.push( '<option name="_edd_activecampaign[]" value='+ i + '>' + lists_array[i] + '</option>' );
Haven't tested yet to confirm, but I _think_ we'll need something in here to add `selected` to the right option?

2021-07-20 14:47 UTC, ashleyfae commented on assets/js/scripts.js
> +					select_lists= document.getElementById( 'edd_activecampaign_checkbox_lists' );
```suggestion
					select_lists = document.getElementById( 'edd_activecampaign_checkbox_lists' );
```

2021-07-20 14:48 UTC, ashleyfae commented on edd-activecampaign.php
> +			add_action( 'wp_ajax_edd_activecampaign_refresh_lists', array( $this, 'refresh_lists' ) );
Can you fix this spacing?

2021-07-20 14:48 UTC, ashleyfae commented on edd-activecampaign.php
> +			add_filter( 'edd_after_setting_output', array( $this, 'add_refresh_button_to_settings_dropdown' ), 10, 2 );
Can you fix this spacing?

2021-07-20 14:50 UTC, ashleyfae reviewed
This is looking great @LisaCee ! I don't think we'll need any major changes, just a few tiny things. :raised_hands:

2021-07-20 16:13 UTC, LisaCee commented on edd-activecampaign.php
> +			add_action( 'wp_ajax_edd_activecampaign_refresh_lists', array( $this, 'refresh_lists' ) );
Yes, sorry. I meant to do that earlier. The whole file is off by a tab and the notices were distracting me.

2021-07-20 16:57 UTC, LisaCee commented on edd-activecampaign.php
> +			echo '<div class="edd_activecampaign_lists" id="edd_activecampaign_checkbox_lists">';
Let me know what you think here. It looks clunky, but I'm not sure how to tidy it up.

2021-07-21 15:19 UTC, robincornett requested changes

2021-07-21 15:19 UTC, robincornett commented on assets/js/scripts.js
> +		button.toggleClass( 'button-disabled' );
Since this is an actual button, what about just setting the `disabled` attribute and removing it as needed, instead of doing the class? That will also actually disable the button, instead of just making it appear to be disabled.

2021-07-21 15:19 UTC, robincornett commented on edd-activecampaign.php
> +		public function render_metabox() {
I know this is how the method came to you, but the `$post` object is actually available to this method if it's passed in as a parameter. I would vote to add `$post` as a parameter and then delete line 603, as it would not be needed.

2021-07-21 15:19 UTC, robincornett commented on edd-activecampaign.php
> +			$wpdb;
This line can just be deleted--the variable isn't used in this method, is it?

2021-07-21 15:19 UTC, robincornett commented on edd-activecampaign.php
> +			return str_replace( '<p', $button . '<p', $output );
In EDD 2.x, the description text is marked up as a `label` and so this is not adding the "refresh" button to the settings screen there at all, although it shows and works nicely in 3.0.

2021-07-21 17:06 UTC, LisaCee commented on edd-activecampaign.php
> +			return str_replace( '<p', $button . '<p', $output );
Nice catch. I've got this working, but let me know if there is a better function to check for 3.0.

2021-07-21 17:29 UTC, robincornett reviewed
I just have a couple of JS questions. This is working well for me, and the button is showing now in 2.x. Looks great!

2021-07-21 17:29 UTC, robincornett commented on assets/js/scripts.js
> +		this.setAttribute( 'disabled', '' );
This could be me not being super great with JS, because I'm not, but why `this` now instead of `button`? `button` had been working for me.

2021-07-21 17:29 UTC, robincornett commented on assets/js/scripts.js
> +	$( '.edd_activecampaign_refresh_lists' ).click( function( e ) {
Also, because I've seen it both ways, is there a difference between doing `.click()` and `.on( 'click' ...` ??? I've seen it both ways and evidently both work, but I don't know why I have seen it both ways.

Also, and maybe this is because of setting the button to be `disabled` now, or something, but if I am doing keyboard navigation and hit enter, the button behavior works, but oddly, the focus jumps to the text input in the metabox above (the purchase shortcode for me). Not sure there why that would be happening and I don't see how it could be because of anything you have done here, but it happened so I'm noting it.

2021-07-21 19:00 UTC, LisaCee commented on assets/js/scripts.js
> +		this.setAttribute( 'disabled', '' );
I used `this` because I was getting an error when I used `button.setAttribute( 'disabled', '' )` and it was causing the button to not work: `Uncaught TypeError: button.setAttribute is not a function.` 

I could work around it by using `button[0].setAttribute( 'disabled', '')` but that seemed like a more hacky method. Which do you prefer?

2021-07-21 19:08 UTC, LisaCee commented on assets/js/scripts.js
> +	$( '.edd_activecampaign_refresh_lists' ).click( function( e ) {
Honestly, I chose `.click` because the function I was modelling this off of used it. I dug into the docs and it looks like it is a shortcut for `.on("click", ...)` https://api.jquery.com/click/

2021-07-21 19:12 UTC, robincornett commented on assets/js/scripts.js
> +		this.setAttribute( 'disabled', '' );
Oh, that would be gross, I agree. But this is all jQuery, right, so could you do this?

```js
button.attr( 'disabled', true );
```

And then `false` to undo it?

2021-07-21 19:15 UTC, robincornett commented
If I edit a download that has no lists selected, this works nicely. But I'm getting this JS error when I have one selected and I try to refresh (on a download edit screen):

```
Uncaught TypeError: data.checked.split is not a function
    at Object.success (scripts.js?ver=1.1.1:19)
    at fire (jquery.js?ver=3.6.0:3500)
    at Object.fireWith [as resolveWith] (jquery.js?ver=3.6.0:3630)
    at done (jquery.js?ver=3.6.0:9796)
    at XMLHttpRequest.<anonymous> (jquery.js?ver=3.6.0:10057)
```

If I `console.log( data )`, it's:

```
action: "edd_activecampaign_refresh_lists"
checked: 3
format: "checkbox"
nonce: "dedcebefaa"
```

2021-07-21 19:21 UTC, LisaCee commented on assets/js/scripts.js
> +		this.setAttribute( 'disabled', '' );
I like your suggestion. The way I had done it was more vanilla JS than jQuery, probably because it's been a while since I've used jQuery. I know we're working to use less jQuery, but since this is already a mash of the two styles I think your suggestion is clearer to read.

2021-07-21 19:25 UTC, robincornett commented on edd-activecampaign.php
> +			echo '<div class="edd_activecampaign_lists" id="edd_activecampaign_checkbox_lists">';
I think that since it's a group of inputs related to one setting, it should be a `fieldset`, similar to a radio input scenario. So the `edd_activecampaign_lists edd-form-group` `div` would become a `fieldset` and I would move it to the top,  and put the "Select the lists..." as the `legend` (I am not sure off the top of my head if a paragraph can go inside of a legend but worth trying). But the inputs/containers themselves look correct to me. I think with each input/label being wrapped in a div element, you should no longer need the `<br />` tags either.

2021-07-21 20:56 UTC, LisaCee commented
Nice catch, @robincornett. It seems that if only 1 list is selected, the index is sent as a string with no commas and thus cannot be split. I'm still working out a solution, but I'll have one for you tomorrow.

2021-07-22 19:00 UTC, robincornett commented on edd-activecampaign.php
> +					echo '<input type="checkbox" name="_edd_activecampaign[]" class="edd-form-group__input" id="' . esc_attr( $list_id ) . '"value="' . esc_attr( $list_id ) . '"' . checked( true, in_array( $list_id
```suggestion
					echo '<input type="checkbox" name="_edd_activecampaign[]" class="edd-form-group__input" id="' . esc_attr( $list_id ) . '" value="' . esc_attr( $list_id ) . '"' . checked( true, in_array( $list_id, $checked ), false ) . '>';
```
I think this is the last thing--and it's working without it but I feel like the space should really be there before the value attribute.

2021-07-22 19:20 UTC, robincornett approved these changes
Really great job on this one @LisaCee !

2021-07-28 13:10 UTC, ashleyfae approved these changes
Brilliant job @LisaCee !

2021-07-28 13:10 UTC, merged